name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "${{ github.workspace }}/postman/collections/Accounts.json" -e "15446980-e786853a-d0d3-47a2-9566-1354d9ddff62" --integration-id "166879-${{ github.run_id }}"
          # Lint your API using Postman CLI
          postman api lint 5635b637-9d9f-45e1-a60d-a119c4be1d27 --integration-id 166879
